name = "cynthia_websites_mini_server"
target = "javascript"
gleam = ">= 1.9.0"
version = "1.1.7-test"



[javascript]
runtime = "bun"
typescript_declarations = true

[dependencies]
# Shared dependencies with the client
gleam_stdlib = "0.59.0"
plinth = ">= 0.5.9 and < 1.0.0"
gleam_javascript = "1.0.0"
gleam_community_colour = "1.4.1"

gleam_json = "2.3.0"
gleam_http = "3.7.2"
gleam_fetch = "1.3.0"

# Other dependencies
argv = "1.0.2"
birl = "1.8.0"
conversation = "2.0.1"
bungibindies = { git = "https://github.com/strawmelonjuice/bungibindies.git", ref = "main" }
cynthia_websites_mini_client = { path = "../cynthia_websites_mini_client" }
edit_distance = "2.0.1"
envoy = "1.0.2"
filepath = "1.1.2"
glam = "2.0.2"
glance = "3.0.0"
gleam_community_ansi = "1.4.3"
gleam_regexp = "1.1.1"
gleam_yielder = "1.1.0"
gleamy_lights = "2.3.0"
javascript_mutable_reference = "1.0.0"
justin = "1.0.1"
ranger = "1.4.0"
simplifile = "2.2.1"
tom = "1.1.1"


webls = "1.5.1"
[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
pprint = ">= 1.0.5 and < 2.0.0"
