[tools]
bun = "latest"
erlang = "27"
gleam = "latest"
watchexec = "latest"

# /================================== Tasks ================================\
# |             These tasks are in comment-split sections                   |
# |               so that they can later be split into                      |
# |                    separate task-toml files.                            |
# \=========================================================================/

# ###########################################################################
# Preparation tasks:
# ###########################################################################

[tasks.generate-prelude]
wait_for = "bun-install"
description = "Generate Gleam prelude for TypeScript FFI"
run = [
  "gleam export typescript-prelude > ./cynthia_websites_mini_client/prelude.ts",
  "gleam export typescript-prelude > ./cynthia_websites_mini_server/prelude.ts",
]

[tasks.bun-install]
description = "Installs Bun's dependencies and prepares the environment"
run = ["bun install", "chmod +x ./generate-ffi"]
run_windows = "bun install"

[tasks.generate-ffi]
description = "Generates themes, CSS, and bundles client into server FFI"
wait_for=["build-client","bun-install"]
dir = "{{ config_root }}"
run = [
  "bun ./generate-ffi",
]
# On Windows, Bun requires TypeScript files to have a `.ts` extension for compatibility.
# Therefore, we need to rename `generate-ffi` to `generate-ffi.ts` before running it.
# Then run it with Bun, and then rename it back.
run_windows = [
  "cmd /c rename generate-ffi generate-ffi.ts",
  "bun ./generate-ffi.ts",
  "cmd /c rename generate-ffi.ts generate-ffi"
]

[tasks.generate-ffi-themes]
description = "Generates themes for the client"
run = [
  "bun ./generate-ffi --only-themes",
]
# also run on Windows
run_windows = [
  "cmd /c rename generate-ffi generate-ffi.ts",
  "bun ./generate-ffi.ts --only-themes",
  "cmd /c rename generate-ffi.ts generate-ffi"
]



[tasks.clean-client]
hide = true
description = "Clean client build artifacts"
run = ["gleam clean", "rm -rf ./build", "rm -rf ./prelude.ts"]
dir = "./cynthia_websites_mini_client"

[tasks.clean-server]
hide = true
description = "Clean server build artifacts"
run = ["gleam clean", "rm -rf ./build", "rm -rf ./prelude.ts", "rm -rf ./src/client_code_generated_ffi.ts"]
dir = "./cynthia_websites_mini_server"


[tasks.clean-all]
description = "Clean all build artifacts and generated files"
depends = ["clean-client", "clean-server"]
run = ["rm -rf ./dist", "rm -rf ./node_modules/"]

[tasks.clean-test]
hide = false
description = "Clean test build artifacts"
run = "rm -rf ./test/*"

# ###########################################################################
# Build tasks:
# ###########################################################################



[tasks.build-client]
run = [
  "gleam build",
  "cat <<EOF   > ./build/dev/javascript/cynthia_websites_mini_client/cynthia_websites_mini_client.ts\nimport { main } from \"./cynthia_websites_mini_client.mjs\";document.addEventListener(\"DOMContentLoaded\", main());\nEOF",
  "bun build \"./build/dev/javascript/cynthia_websites_mini_client/cynthia_websites_mini_client.ts\" --outdir \"./build/bundled/\" --minify-whitespace --minify-syntax --target browser",
]
run_windows = [
  "gleam build",
  """
  echo import { main } from './cynthia_websites_mini_client.mjs'; > .\\build\\dev\\javascript\\cynthia_websites_mini_client\\cynthia_websites_mini_client.ts
  echo document.addEventListener("DOMContentLoaded", main()); >> .\\build\\dev\\javascript\\cynthia_websites_mini_client\\cynthia_websites_mini_client.ts
  """,
  'bun build .\\build\\dev\\javascript\\cynthia_websites_mini_client\\cynthia_websites_mini_client.ts --outdir .\\build\\bundled\\ --minify-whitespace --minify-syntax --target browser',
]
wait_for = "bun-install"
depends = ["bun-install","generate-prelude", "generate-ffi-themes"]
description = "Build the client-side code and bundle it with Bun"
dir = "{{ config_root }}/cynthia_websites_mini_client"


[tasks.build-server]
depends = ["bun-install","generate-prelude", "build-client", "generate-ffi"]
wait_for = ["bun-install", "generate-prelude", "build-client", "generate-ffi"]
description = "Build the server-side code and bundle it with Bun."
run = [
  "gleam build",
  "cat <<EOF   > ./build/dev/javascript/cynthia_websites_mini_server/cynthia_websites_mini_server.ts\nimport { main } from \"./cynthia_websites_mini_server.mjs\";main();\nEOF",
  "bun build \"./build/dev/javascript/cynthia_websites_mini_server/cynthia_websites_mini_server.ts\" --outdir \"./build/bundled/\" --minify-whitespace --minify-syntax --target bun",
]
run_windows = [
  "gleam build",
  """
  echo import { main } from './cynthia_websites_mini_server.mjs'; > .\\build\\dev\\javascript\\cynthia_websites_mini_server\\cynthia_websites_mini_server.ts
  echo main(); >> .\\build\\dev\\javascript\\cynthia_websites_mini_server\\cynthia_websites_mini_server.ts
  """,
  'bun build .\\build\\dev\\javascript\\cynthia_websites_mini_server\\cynthia_websites_mini_server.ts --outdir .\\build\\bundled\\ --minify-whitespace --minify-syntax --target bun',
]
dir = "{{ config_root }}/cynthia_websites_mini_server"


[tasks.check-client]
description = "Check Gleam code in client"
run = ["gleam check"]
dir = "./cynthia_websites_mini_client"


# ###########################################################################
# Development helpers:
# ###########################################################################

[tasks.check-server]
description = "Check Gleam code in server"
run = ["gleam check"]
dir = "./cynthia_websites_mini_server"

[tasks.check-all]
description = "Check Gleam code in both client and server"
depends = ["check-client", "check-server"]


[tasks.fmt-client]
hide = true
description = "Format Gleam code in client"
run = ["gleam format"]
dir = "./cynthia_websites_mini_client"

[tasks.fmt-server]
hide = true
description = "Format Gleam code in server"
run = ["gleam format"]
dir = "./cynthia_websites_mini_server"


[tasks.fmt-all]
description = "Format Gleam code in both client and server"
depends = ["fmt-client", "fmt-server"]


# ###########################################################################
# Publishing tasks:
# ###########################################################################

[tasks.bundle-server]
description = "Bundle the server for production (with shebang)"
depends = ["build-server","build-client"]
run = [
  # Create the dist directory if it doesn't exist.
  "mkdir -p ./dist",
  # Add a shebang line to the bundled file to make it executable.
  "echo '#!/usr/bin/env bun' | cat - ./cynthia_websites_mini_server/build/bundled/cynthia_websites_mini_server.js > ./dist/cynthia_websites_mini_server.js",
  # Make the bundled file executable.
  "chmod +x ./dist/cynthia_websites_mini_server.js"
]
run_windows = [
  # Create the dist directory if it doesn't exist.
  "mkdir .\\dist 2>nul || echo dist already exists",
  # Add a shebang line to the bundled file to make it executable.
  "type .\\cynthia_websites_mini_server\\build\\bundled\\cynthia_websites_mini_server.js >> .\\dist\\cynthia_websites_mini_server.js",
  # Make the bundled file executable (no-op on Windows).
  "echo Skipping chmod on Windows"
]

[tasks.publish]
description = "Prepare a production build (build, bundle, etc.)"
depends = ["build-client", "bundle-server"]

# ###########################################################################
# Run tasks:
# ###########################################################################

[tasks.run-dev]
tools.watchexec = "latest"
depends = "build-server"
description = "Run the Cynthia Mini server in development mode"
run = [
  "bun ../cynthia_websites_mini_server/build/dev/javascript/cynthia_websites_mini_server/cynthia_websites_mini_server.ts"
]
dir = "./test"
[tasks.run-dev-static-server]
tools.watchexec = "latest"
depends = "build-server"
description = "Run the Cynthia Mini server in development mode"
run = [
  "bun ../cynthia_websites_mini_server/build/dev/javascript/cynthia_websites_mini_server/cynthia_websites_mini_server.ts static","bun x serve ./out -s"
]
dir = "./test"


[tasks.run-bundled]
description = "Run the bundled Cynthia Mini server from dist/"
run = [
  "./dist/cynthia_websites_mini_server.js"
]

[tasks.test-client]
hide = true
description = "Run tests for client"
depends = "build-client"
run = ["gleam test --runtime bun"]
dir = "./cynthia_websites_mini_client"

[tasks.test-server]
hide = true
description = "Run tests for server"
depends = "build-server"
run = ["gleam test --runtime bun"]
dir = "./cynthia_websites_mini_server"

[tasks.test-all]
description = "Run tests for both client and server"
depends = ["test-client", "test-server"]
