# This mise.toml only makes sure you can run the same tasks, but they're spawned in the patched version. This should in theory work out just fine.
[tools]
bun = "latest"

[tasks.patch]
description = "Apply patches to the cloned repository"
run = [
  "bun ./patch-script.ts"
]
dir = "{{ config_root }}"

[tasks.patch-first]
hide = true
run = [
  "bun ./patch-script.ts --no-diff"
]
dir = "{{ config_root }}"

[tasks.get_dist]
description = "Get the distribution files to the root of this repository"
depends = "patch-first"
depends_post = "get_dist"
run = [    
  """
  if [ -d {{ config_root }}/patch-target/dist ]; then
    cp -R {{ config_root }}/patch-target/dist {{ config_root }}/dist
  fi
  """,
  """
  if [ -f {{ config_root }}/patch-target/cynthia_websites_mini_client/prelude.ts ]; then
    cp {{ config_root }}/patch-target/cynthia_websites_mini_client/prelude.ts {{ config_root }}/patches/files/cynthia_websites_mini_client/prelude.ts
  fi
  """,
  """
  if [ -f {{ config_root }}/patch-target/cynthia_websites_mini_server/prelude.ts ]; then
    cp {{ config_root }}/patch-target/cynthia_websites_mini_server/prelude.ts {{ config_root }}/patches/files/cynthia_websites_mini_server/prelude.ts
  fi
  """
]
dir = "{{ config_root }}"

[tasks.generate-prelude]
description = "Generate Gleam prelude for TypeScript FFI"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run generate-prelude"]

[tasks.bun-install]
description = "Installs Bun's dependencies and prepares the environment"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run bun-install"]

[tasks.generate-ffi]
description = "Generates themes, CSS, and bundles client into server FFI"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run generate-ffi"]

[tasks.generate-ffi-themes]
description = "Generates themes for the client"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run generate-ffi-themes"]

[tasks.clean-client]
description = "Clean client build artifacts"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run clean-client"]

[tasks.clean-server]
description = "Clean server build artifacts"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run clean-server"]


[tasks.clean-all]
description = "Clean all build artifacts and generated files"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run clean-all"]

[tasks.clean-test]
description = "Clean test build artifacts"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run clean-test"]

# ###########################################################################
# Build tasks:
# ###########################################################################



[tasks.build-client]
description = "Build the client-side code and bundle it with Bun"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run build-client"]


[tasks.build-server]
description = "Build the server-side code and bundle it with Bun."
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run build-server"]


[tasks.check-client]
description = "Check Gleam code in client"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run check-client"]


# ###########################################################################
# Development helpers:
# ###########################################################################

[tasks.check-server]
description = "Check Gleam code in server"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run check-server"]

[tasks.check-all]
description = "Check Gleam code in both client and server"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run check-all"]


[tasks.fmt-client]
description = "Format Gleam code in client"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run fmt-client"]

[tasks.fmt-server]
description = "Format Gleam code in server"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run fmt-server"]


[tasks.fmt-all]
description = "Format Gleam code in both client and server"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run fmt-all"]

[tasks.bundle-server]
description = "Bundle the server for production (with shebang)"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run bundle-server"]


[tasks.publish]
description = "Prepare a production build (build, bundle, etc.)"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run publish"]


[tasks.run-dev]
description = "Run the Cynthia Mini server in development mode"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run run-dev"]

[tasks.run-dev-static-server]
description = "Run the Cynthia Mini server in development mode"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run run-dev-static-server"]

[tasks.run-bundled]
description = "Run the bundled Cynthia Mini server from dist/"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run run-bundled"]

[tasks.test-client]
description = "Run tests for client"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run test-client"]

[tasks.test-server]
description = "Run tests for server"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run test-server"]

[tasks.test-all]
description = "Run tests for both client and server"
depends = "patch-first"
depends_post = "get_dist"
env = { "MISE_CONFIG_ROOT"= "{{ config_root }}/patch-target" }
dir = "{{ config_root }}/patch-target"
run = ["mise run test-all"]