name: Pre-release of cynthiaweb-mini

on:
  push:
    tags:
      - "v*-*"
permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            runner: ubuntu-latest
            arch: x64
            ext: ""
            bin_name: cynthiaweb-mini-linux-x64
          - os: ubuntu
            runner: ubuntu-24.04-arm
            arch: arm64
            ext: ""
            bin_name: cynthiaweb-mini-linux-arm64
          - os: windows
            runner: windows-latest
            arch: x64
            ext: ".exe"
            bin_name: cynthiaweb-mini-windows-x64.exe
          - os: windows
            runner: windows-latest
            arch: arm64
            ext: ".exe"
            bin_name: cynthiaweb-mini-windows-arm64.exe
          - os: macos
            runner: macos-latest
            arch: arm64
            ext: ""
            bin_name: cynthiaweb-mini-macos-arm
          - os: macos
            runner: macos-13
            arch: intel
            ext: ""
            bin_name: cynthiaweb-mini-macos-intel
    steps:
      - uses: actions/checkout@v4
      - name: Install mise and let it install dependencies (Bun, Gleam, etc.)
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
      - name: Build and bundle
        run: |
          bun install
          bun bundle
          bun build --compile dist/cynthia_websites_mini_server.js --outfile ./${{ matrix.bin_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin_name }}
          path: ./${{ matrix.bin_name }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Pre-release ${{ github.ref_name }}
          draft: false
          prerelease: true
          body: |
            Pre-release of cynthiaweb-mini for ${{ github.ref_name }}.
            This is a pre-release version.

            ## Installation
            To install the pre-release version, you can use the following command:

            ```bash
            bun install -g @cynthiaweb/cynthiaweb-mini@${{ github.ref_name }}
            ```
            Note: All releases, including pre-releases, are tagged `latest` on the npm registry. Use a specific version tag if you want to install.

            Or you can download the binaries directly from the release assets.
            The binary install script will with default behaviour not install pre-release versions.

            See <https://cynthiawebsiteengine.github.io/Mini-docs/#/install> for more information.

      - name: Upload Release Assets
        run: |
          for file in ./artifacts/**/cynthiaweb-mini*; do
            gh release upload "${{ github.ref_name }}" "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
